### PR TITLE
r-plotly v4.8.0

### PR DESCRIPTION
**Pull request by halldc**
Depends on https://github.com/conda-forge/r-htmlwidgets-feedstock/pull/4

### CODE REVIEW

**Comment by jdblischak** [comment]
@halldc This recipe is quite old. It uses the outdated conda-build 2 format. Would you be able to also update the recipe format? The easiest way would be to build the recipe using the [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper). Please let me know if you have any questions.

And of course thanks for helping to update conda-forge recipes!

**Comment by halldc** [comment]
@jdblischak Thanks for the tip! I've also updated https://github.com/conda-forge/r-htmlwidgets-feedstock/pull/4

**Comment by halldc** [comment]
@jdblischak All these dependencies need updating before `r-plotly` can get an R 3.5.1 build:

- [x] r-rcolorbrewer
- [x] r-crosstalk
- [x] r-data.table
- [x] r-dplyr
- [x] r-ggplot2
- [x] r-hexbin
- [x] r-httr
- [x] r-lazyeval
- [x] r-purrr
- [x] r-scales
- [x] r-tibble
- [x] r-tidyr
- [x] r-viridislite

This is beyond my capacity though, so hopefully these will get rolled out by the bot.

**Comment by halldc** [comment]
@jdblischak @bgruening This is good to merge 🎉

**Review by jdblischak — APPROVED** [review]

**Pull request merged**
